#!/bin/bash

# Tmux assigns special meaning to certain characters, such as the period,
# so it is necessary to clean up input session names.
#
# The user is responsible for ensuring a given session name has been
# cleaned up before tmux receives it.
#
# Arguments:
# - outvar: the name of an out-variable to store the result in
# - string: the session name to normalise
normalise_session_name()
{
    local _outvar=$1
    local _in=$2
    eval $_outvar="${_in//[.:]/-}"
}

session="${1:-${PWD##*/}}"
normalise_session_name session "${session}"

# "new-s -A" doesn't support session name prefix like "attach-s -t".
if ! tmux attach -t "$session" 2>/dev/null
then
    test $# -gt 0 || exec tmux new-session -s "$session"
    tmux list-sessions 2>/dev/null || printf 1>&2 'tmux server not running.\n'
    exit 1
fi
